stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Test:
  variables:
    GIT_STRATEGY: clone
  stage: test
  image: python:3
  script:
    - export PYTHONPATH="$PYTHONPATH:$(pwd)/NEMO/tests"
    - python -m pip install ./
    - python manage.py test NEMO.tests --settings=test_settings

NEMO-CE dev build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
    - docker logout
  only:
    - schedules
    - master

NEMO-CE Release:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE${CI_COMMIT_TAG:+:}${CI_COMMIT_TAG:-} --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE${CI_COMMIT_TAG:+:}${CI_COMMIT_TAG:-}
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker logout
  only:
    - tags

NEMO-CE PyPI Release:
  variables:
    GIT_STRATEGY: clone
  image: python:3
  stage: build
  script:
    - sed -i "s/^VERSION =.*/VERSION = '$(git describe --tags)'/" setup.py
    - pip install --upgrade pip setuptools wheel twine keyring
    - python setup.py sdist bdist_wheel
    - twine upload --user $PYPI_USER --password $PYPI_PASSWORD ./dist/NEMO_CE*
  only:
    - tags

NEMO-CE dev deploy:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - sudo bash -c 'cd /opt/nemo/ && docker pull registry.gitlab.com/nemo-community/nemo-ce:dev'
    - sudo bash -c 'cd /opt/nemo/ && docker compose up -d nemodev'
  only:
    - schedules
  except:
    - master
  tags: [centos-srv1-shell]
