stages:
  - test
  - build
  - deploy

variables:
  GIT_STRATEGY: clone

.test: &test
  stage: test
  script:
    - python -m pip install ./
    - python ./run_tests.py

Test python 3.9:
  <<: *test
  image: python:3.9

Test python 3.10:
  <<: *test
  image: python:3.10

Test python 3.11:
  <<: *test
  image: python:3.11

Test python 3.12:
  <<: *test
  image: python:3.12

Test python 3.13:
  <<: *test
  image: python:3.13

.test_mysql: &test_mysql
  stage: test
  image: python:3.11
  variables:
    DATABASE_ENGINE: "django.db.backends.mysql"
    DATABASE_HOST: "mysql"
    DATABASE_PORT: 3306
    DATABASE_NAME: "test_db"
    DATABASE_USER: "test_user"
    DATABASE_PASSWORD: "test_password"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: $DATABASE_NAME
    MYSQL_USER: $DATABASE_USER
    MYSQL_PASSWORD: $DATABASE_PASSWORD
  before_script:
    - apt-get update && apt-get install -y default-mysql-client
    - python -m pip install mysqlclient
    - until mysqladmin ping -h"${DATABASE_HOST}" --silent; do echo "Waiting for database..."; sleep 1; done
  script:
    - python -m pip install ./
    - python ./run_tests.py

Test python 3.11 mysql 8.4:
  <<: *test_mysql
  services:
    - name: mysql:8.4
      alias: mysql

Test python 3.11 mysql 9.2:
  <<: *test_mysql
  services:
    - name: mysql:9.2
      alias: mysql


.test_postgres: &test_postgres
  stage: test
  image: python:3.11
  variables:
    DATABASE_ENGINE: "django.db.backends.postgresql"
    DATABASE_HOST: "postgres"
    DATABASE_PORT: 5432
    DATABASE_NAME: "test_db"
    DATABASE_USER: "test_user"
    DATABASE_PASSWORD: "test_password"
    POSTGRES_DB: $DATABASE_NAME
    POSTGRES_USER: $DATABASE_USER
    POSTGRES_PASSWORD: $DATABASE_PASSWORD
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - python -m pip install psycopg2-binary
    - until pg_isready -h "${DATABASE_HOST}" -p "${DATABASE_PORT}" -U "${DATABASE_USER}" --quiet; do echo "Waiting for database..."; sleep 1; done
  script:
    - python -m pip install ./
    - python ./run_tests.py

Test python 3.11 postgres 14:
  <<: *test_postgres
  services:
    - name: postgres:14
      alias: postgres

Test python 3.11 postgres 15:
  <<: *test_postgres
  services:
    - name: postgres:15
      alias: postgres

Test python 3.11 postgres 16:
  <<: *test_postgres
  services:
    - name: postgres:16
      alias: postgres

Test python 3.11 postgres 17:
  <<: *test_postgres
  services:
    - name: postgres:17
      alias: postgres


NEMO-CE dev build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
    - docker logout
  only:
    - schedules
    - master

NEMO-CE Release:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE${CI_COMMIT_TAG:+:}${CI_COMMIT_TAG:-} --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE${CI_COMMIT_TAG:+:}${CI_COMMIT_TAG:-}
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker logout
  only:
    - tags

NEMO-CE PyPI Release:
  image: python:3
  stage: build
  script:
    - sed -i "s/^version =.*/version = '$(git describe --tags)'/" pyproject.toml
    - pip install --upgrade pip build twine
    - python -m build
    - twine upload --user $PYPI_USER --password $PYPI_PASSWORD ./dist/nemo_ce*
  only:
    - tags

NEMO-CE dev deploy:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - sudo bash -c 'cd /opt/nemo/ && docker pull registry.gitlab.com/nemo-community/nemo-ce:dev'
    - sudo bash -c 'cd /opt/nemo/ && docker compose up -d nemodev'
  only:
    - schedules
  tags: [centos-srv1-shell]
